<a href="https://colab.research.google.com/github/nithin1314/FML-lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**0-DIMENSION ARRAY**

In [1]:
import numpy as nk

**zeros()**

In [2]:
a=nk.zeros(20)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
a=nk.zeros(50)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [4]:
nk.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
nk.zeros([5,9])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
a=nk.zeros([5,5],dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
a=nk.zeros(20)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
a=nk.zeros([5,5,5],dtype=int)
print(a)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [9]:
a=nk.zeros([7,9,2],dtype=int)
print(a)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [10]:
a=nk.ones([5,5],dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**FULL()**

In [11]:
a=nk.full([5,5],13,dtype=int)
print(a)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [12]:
a=nk.full([5,56,5],13,dtype=int)
print(a)

[[[13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]
  ...
  [13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]]

 [[13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]
  ...
  [13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]]

 [[13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]
  ...
  [13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]]

 [[13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]
  ...
  [13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]]

 [[13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]
  ...
  [13 13 13 13 13]
  [13 13 13 13 13]
  [13 13 13 13 13]]]


**random.rand()**

In [13]:
a=nk.random.rand(5,5)
print(a)

[[0.7093245  0.21407618 0.43761345 0.74999413 0.48646825]
 [0.91470586 0.22127635 0.2773067  0.77713521 0.41053096]
 [0.52524852 0.62781469 0.59400835 0.07237548 0.06834178]
 [0.45792218 0.61544994 0.63120078 0.24290714 0.1093287 ]
 [0.23781261 0.1950581  0.89523413 0.43637902 0.55121358]]


In [14]:
a=nk.random.rand(5,5,34)
print(a)

[[[1.60418574e-01 3.60180833e-01 2.91199194e-01 1.02326747e-01
   8.70766211e-01 5.14264245e-02 8.45906386e-01 8.51881128e-02
   1.98302301e-01 8.69589090e-01 5.01332234e-02 3.00721883e-01
   5.37012760e-01 5.61295773e-01 6.94656823e-01 8.28652290e-01
   9.75478325e-01 9.54624173e-01 2.43503088e-01 3.21549561e-01
   8.83788172e-01 2.90023968e-01 2.56915083e-01 7.61173485e-01
   5.09547882e-01 2.26806256e-02 7.86750400e-01 6.64269385e-01
   4.93017898e-01 5.70844598e-01 3.30566933e-02 4.25662166e-01
   3.17829944e-01 5.58036739e-01]
  [2.16635995e-01 9.35122189e-01 9.12605816e-01 8.86781966e-01
   4.25216061e-01 3.05272659e-01 4.33304276e-01 6.98205765e-01
   2.65652030e-01 7.18842148e-01 5.39810550e-01 5.36836940e-01
   1.92037607e-01 4.58070546e-01 2.25953250e-01 8.38897659e-01
   8.07164731e-01 2.80877614e-01 6.93654701e-01 1.44791546e-01
   7.67286093e-01 6.54430335e-01 7.90007379e-01 3.93172593e-01
   4.98717481e-01 9.81731416e-01 6.80897558e-02 9.44295580e-01
   1.53770513e-01 3.3

**eye()**

In [15]:
a=nk.eye(69)
print(a)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


**numerical range()**

**arange()**

In [16]:
a=nk.arange(1,100,4)
print(a)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [17]:
a=nk.arange(1,100,4,dtype=float)
print(a)

[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41. 45. 49. 53. 57. 61. 65. 69.
 73. 77. 81. 85. 89. 93. 97.]


**reshape()**

In [18]:
a=nk.arange(1,20,2)
a.reshape(10,1)


array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [19]:
a.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

**linspace()**

In [20]:
a=nk.linspace(10,100,10)
print(a)


[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [21]:
a=nk.linspace(10,100,10,endpoint=False)
print(a)


[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [22]:
a=nk.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)
print(a)


(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


**logspace()**

In [23]:
import numpy as nk
a=nk.logspace(1,10,2)
print(a)

[1.e+01 1.e+10]


In [24]:
a=nk.logspace(1,10,10)
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


**slicing**

In [25]:
a=nk.array([[23,56,432,422,9],[352,743,5656,25]])
print(a)

[list([23, 56, 432, 422, 9]) list([352, 743, 5656, 25])]


<ipython-input-25-5fae5109b697>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=nk.array([[23,56,432,422,9],[352,743,5656,25]])


In [26]:
a[1][1]


743

In [27]:
h=nk.arange(10,500,100)
print(h)

[ 10 110 210 310 410]


**copy**

In [28]:
a=nk.array([[1,2,3,4,5],[2,4,6,323,453]])
print(a)

[[  1   2   3   4   5]
 [  2   4   6 323 453]]


In [29]:
b=nk.copy(a)
print(b)
print(a)

[[  1   2   3   4   5]
 [  2   4   6 323 453]]
[[  1   2   3   4   5]
 [  2   4   6 323 453]]


In [30]:
c=nk.copy(b)
c

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

**view**

In [31]:
c=b.view()
c
b

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

In [32]:
c[1][2]

6

**sort**

In [33]:
nk.sort(c)

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

In [34]:
s=c.reshape(5,2)
print(s)

[[  1   2]
 [  3   4]
 [  5   2]
 [  4   6]
 [323 453]]


**axis**

In [35]:
nk.sort(c,axis=0)

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

In [36]:
nk.sort(c,axis=1)

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

In [37]:
a=nk.array([(b'a',99.3),(b'r',98.5)],dtype=[('name','S1'),('perc','<f8')])
print(a)

[(b'a', 99.3) (b'r', 98.5)]


**reshape**

In [38]:
c.reshape(2,5)

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6, 323, 453]])

**append**

In [39]:
a=nk.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [40]:
b=nk.linspace(10,100,20)
print(b)

[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]


In [41]:
nk.append(a,b)

array([ 10.        ,  20.        ,  30.        ,  40.        ,
        50.        ,  60.        ,  70.        ,  80.        ,
        90.        , 100.        ,  10.        ,  14.73684211,
        19.47368421,  24.21052632,  28.94736842,  33.68421053,
        38.42105263,  43.15789474,  47.89473684,  52.63157895,
        57.36842105,  62.10526316,  66.84210526,  71.57894737,
        76.31578947,  81.05263158,  85.78947368,  90.52631579,
        95.26315789, 100.        ])

In [42]:
nk.append(a,b).reshape(1,30)

array([[ 10.        ,  20.        ,  30.        ,  40.        ,
         50.        ,  60.        ,  70.        ,  80.        ,
         90.        , 100.        ,  10.        ,  14.73684211,
         19.47368421,  24.21052632,  28.94736842,  33.68421053,
         38.42105263,  43.15789474,  47.89473684,  52.63157895,
         57.36842105,  62.10526316,  66.84210526,  71.57894737,
         76.31578947,  81.05263158,  85.78947368,  90.52631579,
         95.26315789, 100.        ]])

**insert**

In [43]:
nk.insert(a,4,[23,54])

array([ 10.,  20.,  30.,  40.,  23.,  54.,  50.,  60.,  70.,  80.,  90.,
       100.])

In [44]:
nk.insert(b,4,[45,24])

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        45.        ,  24.        ,  28.94736842,  33.68421053,
        38.42105263,  43.15789474,  47.89473684,  52.63157895,
        57.36842105,  62.10526316,  66.84210526,  71.57894737,
        76.31578947,  81.05263158,  85.78947368,  90.52631579,
        95.26315789, 100.        ])

**delete**

In [45]:
nk.delete(a,2)

array([ 10.,  20.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**concatenate**

In [46]:
nk.concatenate((a,b))

array([ 10.        ,  20.        ,  30.        ,  40.        ,
        50.        ,  60.        ,  70.        ,  80.        ,
        90.        , 100.        ,  10.        ,  14.73684211,
        19.47368421,  24.21052632,  28.94736842,  33.68421053,
        38.42105263,  43.15789474,  47.89473684,  52.63157895,
        57.36842105,  62.10526316,  66.84210526,  71.57894737,
        76.31578947,  81.05263158,  85.78947368,  90.52631579,
        95.26315789, 100.        ])

In [47]:
nk.concatenate((a,b),axis=0)

array([ 10.        ,  20.        ,  30.        ,  40.        ,
        50.        ,  60.        ,  70.        ,  80.        ,
        90.        , 100.        ,  10.        ,  14.73684211,
        19.47368421,  24.21052632,  28.94736842,  33.68421053,
        38.42105263,  43.15789474,  47.89473684,  52.63157895,
        57.36842105,  62.10526316,  66.84210526,  71.57894737,
        76.31578947,  81.05263158,  85.78947368,  90.52631579,
        95.26315789, 100.        ])

**stack**

In [48]:
a=nk.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [49]:
b=nk.array([0,9,8,7,6,5])
print(b)

[0 9 8 7 6 5]


In [50]:
nk.stack((a,b))

array([[1, 2, 3, 4, 5, 6],
       [0, 9, 8, 7, 6, 5]])

In [51]:
nk.stack((a,b),axis=1)

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6],
       [6, 5]])

In [52]:
a=nk.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [53]:
b=nk.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [54]:
nk.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [55]:
nk.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [56]:
nk.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

**split**

In [57]:
a=nk.arange(5,65,5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [58]:
nk.split(a,2)

[array([ 5, 10, 15, 20, 25, 30]), array([35, 40, 45, 50, 55, 60])]

In [59]:
nk.split(a,1)

[array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])]

In [60]:
s1,s2=nk.split(a,2)

**where**

In [61]:
nk.where(a==10)

(array([1]),)

In [62]:
nk.where(a%2==0)

(array([ 1,  3,  5,  7,  9, 11]),)

 **search sorted**

np.searchsorted(a,10)

arthimetic operations

In [63]:
a=nk.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [64]:
b=nk.array([[50,60],[70,80]])
print(b)

[[50 60]
 [70 80]]


In [65]:
nk.add(a,b)

array([[ 60,  80],
       [100, 120]])

In [66]:
nk.subtract(a,b)

array([[-40, -40],
       [-40, -40]])

In [67]:
nk.multiply(a,b)

array([[ 500, 1200],
       [2100, 3200]])

In [68]:
nk.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [69]:
nk.exp(a)

array([[2.20264658e+04, 4.85165195e+08],
       [1.06864746e+13, 2.35385267e+17]])

In [70]:
nk.sqrt(b)

array([[7.07106781, 7.74596669],
       [8.36660027, 8.94427191]])

 **array functions**

min

In [71]:
import numpy as nk
a=nk.array([[100,200],[300,400],[500,600]])
a

array([[100, 200],
       [300, 400],
       [500, 600]])

In [72]:
nk.min(a)

100

max

In [73]:
nk.max(a)

600

In [74]:
nk.max(a,axis=1)

array([200, 400, 600])

In [75]:
nk.max(a,axis=1)

array([200, 400, 600])

sum

In [76]:
nk.sum(a)

2100

In [77]:
nk.sum(a,axis=1)

array([ 300,  700, 1100])

In [78]:
nk.sum(a,axis=0)

array([ 900, 1200])

In [79]:
nk.sum(a,axis=1)

array([ 300,  700, 1100])

In [80]:
nk.sum(a,axis=0)

array([ 900, 1200])

mean

In [81]:
nk.mean(a)

350.0

In [82]:
nk.mean(a,axis=0)

array([300., 400.])

In [83]:
nk.mean(a,axis=1)

array([150., 350., 550.])

median

In [84]:
nk.median(a)

350.0

In [85]:
nk.median(a,axis=1)

array([150., 350., 550.])

**var**

In [86]:
nk.var(a)

29166.666666666668

In [87]:
nk.var(a,axis=1)

array([2500., 2500., 2500.])

In [88]:
nk.var(a,axis=0)

array([26666.66666667, 26666.66666667])

**std**

In [89]:
nk.std(a)

170.78251276599332

In [90]:
nk.std(a,axis=1)

array([50., 50., 50.])

In [91]:
nk.std(a,axis=0)

array([163.29931619, 163.29931619])

In [92]:
import numpy as np
a=np.array(200)
print(a)

200


In [93]:
import numpy as nk
a=nk.array(1411)
print(a)

1411


In [94]:
import numpy as nk
a=nk.array(11)
print(a)

11


In [95]:
import numpy as nk
a=nk.array(141)
print(a)

141


**1-DIMENSION ARRAY**

In [96]:
import numpy as nn
a=nn.array([200,300,400])
print(a)


[200 300 400]


In [97]:
import numpy as nn
a=nn.array([299,300,400])
print(a)


[299 300 400]


In [98]:
import numpy as nn
a=nn.array([200,20,400])
print(a)


[200  20 400]


In [99]:
import numpy as nn
a=nn.array([200,300,45])
print(a)


[200 300  45]


**2-DIMENSION ARRAY**

In [100]:
import numpy as nn
a=nn.array([[200,300],[400,500]])
print(a)
a[1][0]


[[200 300]
 [400 500]]


400

In [101]:
import numpy as nn
a=nn.array([[200,300,400],[395,56,6]])
print(a)
a[0][1]

[[200 300 400]
 [395  56   6]]


300

In [102]:
import numpy as nn
a=nn.array([[200,300,400],[395,56,6]])
print(a)
a[0][0]

[[200 300 400]
 [395  56   6]]


200

In [103]:
import numpy as nn
a=nn.array([[200,300,400],[395,56,6]])
print(a)
a[1][1]

[[200 300 400]
 [395  56   6]]


56

**3-DIMENSION ARRAY**

In [104]:
import numpy as nk
a=nk.array([[[200,300],[400,500]],[[500,600],[700,800]]])
print(a)
a[0][1][0]

[[[200 300]
  [400 500]]

 [[500 600]
  [700 800]]]


400

In [105]:
import numpy as nk
a=nk.array([[[200,300],[400,500]],[[500,600],[700,800]]])
print(a)
a[0][1][1]

[[[200 300]
  [400 500]]

 [[500 600]
  [700 800]]]


500

In [106]:
import numpy as nk
a=nk.array([[[200,300],[400,500]],[[500,600],[700,800]]])
print(a)
a[1][1][0]

[[[200 300]
  [400 500]]

 [[500 600]
  [700 800]]]


700

In [107]:
import numpy as nk
a=nk.array([[[200,300],[400,500]],[[500,600],[700,800]]])
print(a)
a[0][0][0]

[[[200 300]
  [400 500]]

 [[500 600]
  [700 800]]]


200

**as array()**

In [108]:
import numpy as nk
a=[200,300,400,500]
b=np.asarray(a)
print(b)

[200 300 400 500]


In [109]:
import numpy as nk
a=[200,300,400,500]
b=np.asarray(a,dtype=float)
print(b)

[200. 300. 400. 500.]


**as array of C row**

In [110]:
import numpy as nk
a=[200,300,400,500]
b=np.asarray(a,order="C")
print(b)

[200 300 400 500]


In [111]:
import numpy as nk
a=[[200,300],[400,500]]
b=np.asarray(a,order="C")
print(b)
for i in nk.nditer(b):
  print(i)

[[200 300]
 [400 500]]
200
300
400
500


**as array of F column**

In [112]:
import numpy as nk
a=[[200,300],[400,500]]
b=np.asarray(a,order="f")
print(b)
for i in nk.nditer(b):
  print(i)

[[200 300]
 [400 500]]
200
400
300
500


**frombuffer()**

In [113]:
import numpy as nk
a=b"I AM GOING TO BECOME HOKAGE"
nk.frombuffer(a,dtype="S1")

array([b'I', b' ', b'A', b'M', b' ', b'G', b'O', b'I', b'N', b'G', b' ',
       b'T', b'O', b' ', b'B', b'E', b'C', b'O', b'M', b'E', b' ', b'H',
       b'O', b'K', b'A', b'G', b'E'], dtype='|S1')

In [114]:
import numpy as nk
a=b"I AM GOING TO BECOME HOKAGE"
nk.frombuffer(a,dtype="S1",count=14)

array([b'I', b' ', b'A', b'M', b' ', b'G', b'O', b'I', b'N', b'G', b' ',
       b'T', b'O', b' '], dtype='|S1')

In [115]:
import numpy as nk
a=b"I AM GOING TO BECOME HOKAGE"
nk.frombuffer(a,dtype="S1",offset=12)

array([b'O', b' ', b'B', b'E', b'C', b'O', b'M', b'E', b' ', b'H', b'O',
       b'K', b'A', b'G', b'E'], dtype='|S1')

In [116]:
import numpy as nk
a=b"I AM GOING TO BECOME HOKAGE"
nk.frombuffer(a,dtype="S1",count=4,offset=12)

array([b'O', b' ', b'B', b'E'], dtype='|S1')

**fromiter()**

In [117]:
import numpy as nk
a=([200,300,400])
nk.fromiter(a,dtype="S1",count=3)

array([b'2', b'3', b'4'], dtype='|S1')

In [118]:
import numpy as nk
a=([200,300,400])
nk.fromiter(a,dtype=int,count=3)

array([200, 300, 400])

In [119]:
import numpy as nk
a=([200,300,400])
nk.fromiter(a,dtype=float,count=3)

array([200., 300., 400.])

In [120]:
import pandas as ns
ks=ns.read_csv('/content/drive/MyDrive/datasets/71 Centuries of Virat Kohli.csv')
ks


Score Out/Not Out       Against  Batting Order  Inn.  Strike Rate  \
0     116         Out     Australia              6     2          NaN   
1     103         Out   New Zealand              5     2          NaN   
2     103         Out       England              5     2          NaN   
3     107         Out     Australia              5     2          NaN   
4     119         Out  South Africa              4     1          NaN   
..    ...         ...           ...            ...   ...          ...   
66    116         Out     Australia              3     1        96.67   
67    123         Out     Australia              3     2       129.47   
68    120         Out   West Indies              3     1        96.00   
69    114     Not Out   West Indies              3     2       115.15   
70    122     Not Out    Afganistan              1     1       200.00   

                                   Venue         Column1   H/A        Date  \
0                          Adelaide Oval        Adelaide  Away  24-01-2012   
1                 M. Chinnaswamy Stadium       Bangalore  Home  31-08-2012   
2   Vidarbha Cricket Association Stadium          Nagpur  Home  13-12-2012   
3              M. A. Chidambaram Stadium         Chennai  Home  22-02-2013   
4                      Wanderers Stadium    Johannesburg  Away  18-12-2013   
..                                   ...             ...   ...         ...   
66  Vidarbha Cricket Association Stadium          Nagpur  Home  05-03-2019   
67            JSCA International Stadium          Ranchi  Home  08-03-2019   
68                     Queen's Park Oval   Port of Spain  Away  11-08-2019   
69                     Queen's Park Oval   Port of Spain  Away  14-08-2019   
70   Dubai International Cricket Stadium           Dubai  Away  08-09-2022   

   Result Format Man of the Match Captain  Unnamed: 14  
0    Lost   Test               No      No          NaN  
1     Won   Test              Yes      No          NaN  
2   Drawn   Test               No      No          NaN  
3     Won   Test               No      No          NaN  
4   Drawn   Test               No      No          NaN  
..    ...    ...              ...     ...          ...  
66    Won    ODI              Yes     Yes          NaN  
67   Lost    ODI               No     Yes          NaN  
68    Won    ODI              Yes     Yes          NaN  
69    Won    ODI              Yes     Yes          NaN  
70    Won   T20I              Yes      No          NaN  

[71 rows x 15 columns]